server:
  port: 8076
  servlet:
    session:
      timeout: 1800s

spring:
  #设置编码
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/short_url?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 199725
  #静态资源配置
  resources:
    static-locations: classpath:/static/
  #thymeleaf模板引擎配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  #Redis配置
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: Xingxing9725 # Redis服务器连接密码（默认为空）
    database: 0 #Redis数据库索引（默认为0）
    timeout: 500 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接

logging:
  level:
    com.bluewind.easytask: info
    org.springframework: warn